name: Deployment pipeline

on:
  push:
    branches: ["main", "master"]
env:
  ELECTRON_EXTRA_LAUNCH_ARGS: "--disable-gpu"

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Install dependencies
        run: npm install
      - name: Check style
        run: npm run eslint
      - name: Run unit tests
        run: npm run test
      - name: e2e tests
        uses: cypress-io/github-action@v5
        with:
          build: npm run build
          command: npm run test:e2e
          start: npm run start-prod
          browser: chrome
          wait-on: http://localhost:5000
